### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by Tamaized** [eerussianguy/Rainbow-Oaks#1]
All 3 Files here: https://github.com/eerussianguy/Rainbow-Oaks/tree/main/src/main/resources/assets/rainbowoaks/textures/block

Assets do not fall under LGPL v2.1 infact they cannot work under that license, and thus currently fall under All Rights Reserved.
We already spoke and planned to touch on this fact in our README.md a while ago but haven't gotten around to it. We did think about applying an actual reasonable license but we're not at that point yet, haven't even spoken to some of our art contributors about it yet.

The person who commissioned you was already confronted about this once before and had told us they'd offer their own textures but that obviously didn't happen.

**Comment by eerussianguy** [comment]
Though you are not a lawyer, I have little faith in my ability to appeal a copyright claim. So I have changed the offending assets.

I had not been made aware by the person who commissioned the mod. It's not worth articulating my personal views on the subject here besides that at the end of this day it says little about the intent behind the licensing scheme and a lot about who you are as a person.
